-- CTE example: 
;with cte as (
SELECT t1.PACKAGEOBJID
		,t1.STATEOBJID
		,t1.STATENAME
		,t1.ENVOBJID
		,t1.STARTEXECDTIME AS STARTEXECDTIME
		,(case when t1.STATENAME = 'Finalizado' then t1.STARTEXECDTIME else LEAD (t1.STARTEXECDTIME) OVER (ORDER BY t1.STARTEXECDTIME)  end) AS ENDEXECDTIME
		,t1.USROBJID 
		--,ROW_NUMBER() OVER(PARTITION BY t1.PACKAGEOBJID ORDER BY T1.STARTEXECDTIME ) AS RWNUM2
		FROM (
SELECT 	 X.PACKAGEOBJID
		,X.STATEOBJID
		,X.STATENAME
		,X.ENVOBJID
		,X.EXECDTIME AS STARTEXECDTIME
		,X.USROBJID
		,ROW_NUMBER() OVER(PARTITION BY  X.PACKAGEOBJID, X.STATENAME
		ORDER BY X.EXECDTIME ASC) AS RWNUM
		,X.ACTION	
FROM  X.X X WHERE PACKAGEOBJID = 8557 
) AS T1
WHERE T1.RWNUM = 1)

select * from cte

-- COALESCE example: 
COALESCE((CONVERT(VARCHAR(8),dateadd(second,creation_date,'19691231 19:00:00'),112))