DECLARE @ID INT = 1, @VAR VARCHAR(250), @SQL NVARCHAR(MAX)
DECLARE @TABLE AS TABLE(ID INT IDENTITY(1,1), CAMPO VARCHAR(250))

INSERT INTO @TABLE (CAMPO)
SELECT COLUMN_NAME CAMPO
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'Rep' AND  ( DATA_TYPE = 'varchar' OR DATA_TYPE = 'nvarchar')

IF OBJECT_ID('tempdb..#PRU') IS NOT NULL
DROP TABLE #PRU

SELECT * 
	INTO #PRU
	FROM [CMDB].[Rep]


WHILE @ID <= (SELECT ID FROM @TABLE WHERE ID = @ID)

BEGIN

	SET @VAR = '['+(SELECT CAMPO FROM @TABLE WHERE ID = @ID)+']'

	SET @SQL ='UPDATE TBL SET '+@VAR+' = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE('+@VAR+','';'',''''),''#'',''''),''$'',''''),''!'',''''),''%'',''''),''\t'',''''),''\r'',''''),
	''\n'',''''),''\'',''''),''*'','''')
	FROM #PRU TBL'

	EXEC(@SQL)

	SET @ID = @ID +1
END

SELECT * FROM #PRU